language: csharp
dist: trusty
mono: none
dotnet: 2.0.0

script:
- dotnet run -p text-line-importer-from-text-file/text-line-importer-from-text-file.csproj text-line-importer-from-text-file/text-file-input.txt
